net: DBnet
seed: 1
run_eval: True
eval_iter: 20
device_target: "Ascend"
context_mode: "graph"
mix_precision: True
backbone:
    initializer: resnet50
    pretrained: True
    pretrained_ckpt: "/data1/zhaoting/temp/resnet50-19c8e357.ckpt"
segdetector:
    in_channels: [256, 512, 1024, 2048]  # R18: [64, 128, 256, 512]
    inner_channels: 256
    k: 50
    bias: False
    adaptive: True
    serial: False
loss:
    eps: 0.000001
    l1_scale: 10
    bce_scale: 5  # focal:0.5  dice:1.6  bceloss:1
    bce_replace: bceloss # diceloss / focalloss / bceloss
optimizer:
    type: sgd
    lr:
        base_lr: 0.02
        target_lr: 0.0
        warmup_epoch: 3
        factor: 0.9
    momentum: 0.9
    weight_decay: 0.0001
dataset:
    class: TotalTextDataloader
    is_show: False
    is_icdar2015: True
    num_workers: 7
    prefetch_size: 42
    short_side: 736
    random_angle: [-10, 10]
    random_crop:
        max_tries: 100
        min_crop_side_ratio: 0.1
train:
    img_format: '.jpg'
    img_dir: "/data1/zhaoting/dbnet/data/train_images/"
    gt_dir: "/data1/zhaoting/dbnet/data/train_gts/"
    is_continue_training: False
    last_ckpt_path: ""
    start_epoch_num: 0
    total_epochs: 1500
    batch_size: 8
    save_steps: 630
    max_checkpoints: 5
    is_transform: True
    is_eval_before_saving: True
    shrink_ratio: 0.4
    min_text_size: 8
    thresh_min: 0.3
    thresh_max: 0.7
    dataset_sink_mode: True
eval:
    img_format: '.jpg'
    img_dir: "/data1/zhaoting/dbnet/data/test_images/"
    gt_dir: "/data1/zhaoting/dbnet/data/test_gts/"
    show_images: False
    image_dir: './outputs_test/'
    thresh: 0.3
    box_thresh: 0.55
    max_candidates: 1000
    unclip_ratio: 1.5
    polygon: False
    dest: binary
